name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: flake8
      run: |
        make flake8
    - name: yapf
      run: |
        make py-format
    - name: addlicense
      run: |
        make addlicense
