# Action name
name: Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Build source distribution
      run: |
        python3 setup.py sdist
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: tarball
        path: dist/*.tar.gz
  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: tarball
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
